### ISSUE TITLE
Running the demo app with gulp

### ISSUE THREAD

**Issue by rawad1989** [DarkPark/stb-demo#6]
AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (/Volumes/Folders/stb_env_testing/node_modules/undertaker/lib/set-task.js:10:3)
    at Gulp.task (/Volumes/Folders/stb_env_testing/node_modules/undertaker/lib/task.js:13:8)
    at Object.<anonymous> (/Volumes/Folders/stb_env_testing/tasks/build.js:14:6)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at /Volumes/Folders/stb_env_testing/gulpfile.js:28:5 {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}

**Comment by DarkPark** [comment]
https://github.com/DarkPark/stb is not maintained anymore.
You can take a look at this alternative - https://github.com/stbsdk
